Repository rappasoft/laravel-livewire-tables, pull requests merged in 2023-11, with the labels that each got.

#1503 V3 - Filter DTOs
  CHANGELOG.md
  resources/views/components/table/tr/footer.blade.php
  resources/views/components/table/tr/secondary-header.blade.php
  resources/views/components/tools/toolbar.blade.php
  resources/views/components/tools/toolbar/items/filter-button.blade.php
  resources/views/components/tools/toolbar/items/filter-popover.blade.php
  resources/views/components/tools/toolbar/items/filter-slidedown.blade.php
  resources/views/datatable.blade.php
  src/DataTableComponent.php
  src/DataTransferObjects/FilterGenericData.php
  src/Traits/Configuration/FilterConfiguration.php
  src/Traits/Helpers/FilterHelpers.php
  src/Traits/WithFilters.php
  src/Views/Filter.php
  src/Views/Filters/DateFilter.php
  src/Views/Filters/DateRangeFilter.php
  src/Views/Filters/DateTimeFilter.php
  src/Views/Filters/MultiSelectDropdownFilter.php
  src/Views/Filters/MultiSelectFilter.php
  src/Views/Filters/NumberFilter.php
  src/Views/Filters/NumberRangeFilter.php
  src/Views/Filters/SelectFilter.php
  src/Views/Filters/TextFilter.php
  src/Views/Traits/Configuration/FilterConfiguration.php
  src/Views/Traits/Helpers/ColumnHelpers.php
  src/Views/Traits/Helpers/FilterHelpers.php
  tests/Traits/Helpers/ColumnHelpersTest.php
  tests/Views/Traits/Helpers/ColumnHelpersTest.php
  tests/Views/Traits/Helpers/FilterHelpersTest.php
Labels: In Progress

#1556 Add Anonymous Columns to the docs
  docs/columns/anonymous_columns.md
Labels: documentation, Version 3

#1558 v3 Splitting of JS Files
  .gitattributes
  CHANGELOG.md
  resources/js/laravel-livewire-tables.js
  resources/js/laravel-livewire-tables.min.js
  resources/js/partials/filter-date-range.js
  resources/js/partials/filter-date-range.min.js
  resources/js/partials/filter-number-range.js
  resources/js/partials/filter-number-range.min.js
  resources/js/partials/reorder.js
  resources/js/partials/reorder.min.js
Labels: bug, enhancement, Version 3

#1545 Removed a UI bug where the table header + column selector has slight white pixels on top
  resources/views/components/table.blade.php
  resources/views/components/tools/toolbar/items/column-select.blade.php
Labels: bug, In Progress
